-- ------------------------------------------------------
-- VB version 2.4 SQL Script
-- ------------------------------------------------------

ALTER TABLE `language_code` CHANGE `language_code` `language_code` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `users_language` CHANGE `language_code` `language_code` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `users_language_projects` CHANGE `language_code` `language_code` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `language_interface` CHANGE `language_code` `language_code` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';


-- Copy existing records from users_language to users_langauge_projects table
INSERT IGNORE INTO users_language_projects SELECT ul.user_id, ul.language_code, uo.ontology_id FROM users_language ul INNER JOIN users_ontology	uo WHERE ul.user_id=uo.user_id;

-- Copy existing records from users_groups to users_groups_projects table
INSERT IGNORE INTO users_groups_projects SELECT ug.users_id, ug.users_group_id, uo.ontology_id FROM users_groups_map ug INNER JOIN users_ontology uo WHERE ug.users_id=uo.user_id;

-- Give administrator project management priviledge
INSERT IGNORE INTO `permission_group_map` (`users_groups_id`, `permission_id`) VALUES ('1', '26');


-- Fix permission for Term editor
DELETE FROM `permission_functionality_map` WHERE group_id=5;
INSERT IGNORE INTO `permission_functionality_map` VALUES(74, 5, 8),(74, 5, 7),(74, 5, 5),(74, 5, 4),(74, 5, 3),(74, 5, 2),(74, 5, 1),(17, 5, 8),(17, 5, 7),(17, 5, 5),(17, 5, 4),(17, 5, 3),(17, 5, 2),(17, 5, 1),(16, 5, 8),(16, 5, 7),(16, 5, 5),(16, 5, 4),(16, 5, 3),(16, 5, 2),(16, 5, 1),(15, 5, 8),(15, 5, 7),(15, 5, 5),(15, 5, 4),(15, 5, 3),(15, 5, 2),(15, 5, 1),(14, 5, 8),(14, 5, 7),(14, 5, 5),(14, 5, 4),(14, 5, 3),(14, 5, 2),(14, 5, 1),(13, 5, 8),(13, 5, 7),(13, 5, 5),(13, 5, 4),(13, 5, 3),(13, 5, 2),(13, 5, 1),(12, 5, 8),(12, 5, 7),(12, 5, 5),(12, 5, 4),(12, 5, 3),(12, 5, 2),(12, 5, 1),(11, 5, 8),(11, 5, 7),(11, 5, 5),(11, 5, 4),(11, 5, 3),(11, 5, 2),(11, 5, 1),(10, 5, 8),(10, 5, 7),(10, 5, 5),(10, 5, 4),(10, 5, 3),(10, 5, 2),(10, 5, 1),(9, 5, 8),(9, 5, 7),(9, 5, 5),(9, 5, 4),(9, 5, 3),(9, 5, 2),(9, 5, 1),(8, 5, 8),(8, 5, 7),(8, 5, 5),(8, 5, 4),(8, 5, 3),(8, 5, 2),(8, 5, 1),(7, 5, 8),(7, 5, 7),(7, 5, 5),(7, 5, 4),(7, 5, 3),(7, 5, 2),(7, 5, 1),(6, 5, 8),(6, 5, 7),(6, 5, 5),(6, 5, 4),(6, 5, 3),(6, 5, 2),(6, 5, 1);

--
-- Add permission for Project Manager --
--
-- Adding data for table `permission_group_map`
INSERT IGNORE INTO `permission_group_map` (`users_groups_id`, `permission_id`) 
SELECT users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' 
UNION ALL 
SELECT users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 10 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 13 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 15 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 18 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 19 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 20 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 21 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 22 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 23 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 25 FROM users_groups WHERE users_groups_name='Project manager'
UNION ALL 
SELECT users_groups_id, 26 FROM users_groups WHERE users_groups_name='Project manager'
;

-- Adding data for table `permission_functionality_map`
--INSERT IGNORE INTO `permission_functionality_map` (`function_id`, `group_id`, `status`) VALUES(81, 15, 8),(81, 15, 7),(81, 15, 6),(81, 15, 5),(81, 15, 4),(81, 15, 3),(81, 15, 2),(81, 15, 1),(80, 15, 8),(80, 15, 7),(80, 15, 6),(80, 15, 5),(80, 15, 4),(80, 15, 3),(80, 15, 2),(80, 15, 1),(79, 15, 8),(79, 15, 7),(79, 15, 6),(79, 15, 5),(79, 15, 4),(79, 15, 3),(79, 15, 2),(79, 15, 1),(78, 15, 8),(78, 15, 7),(78, 15, 6),(78, 15, 5),(78, 15, 4),(78, 15, 3),(78, 15, 2),(78, 15, 1),(77, 15, 8),(77, 15, 7),(77, 15, 6),(77, 15, 5),(77, 15, 4),(77, 15, 3),(77, 15, 2),(77, 15, 1),(76, 15, 8),(76, 15, 7),(76, 15, 6),(76, 15, 5),(76, 15, 4),(76, 15, 3),(76, 15, 2),(76, 15, 1),(75, 15, 8),(75, 15, 7),(75, 15, 5),(75, 15, 4),(75, 15, 3),(75, 15, 2),(75, 15, 1),(74, 15, 8),(74, 15, 7),(74, 15, 5),(74, 15, 4),(74, 15, 3),(74, 15, 2),(74, 15, 1),(73, 15, 8),(73, 15, 7),(73, 15, 5),(73, 15, 4),(73, 15, 3),(73, 15, 2),(73, 15, 1),(72, 15, 8),(72, 15, 7),(72, 15, 5),(72, 15, 4),(72, 15, 3),(72, 15, 2),(72, 15, 1),(64, 15, 8),(64, 15, 7),(64, 15, 5),(64, 15, 4),(64, 15, 3),(64, 15, 2),(64, 15, 1),(63, 15, 8),(63, 15, 7),(63, 15, 5),(63, 15, 4),(63, 15, 3),(63, 15, 2),(63, 15, 1),(62, 15, 8),(62, 15, 7),(62, 15, 5),(62, 15, 4),(62, 15, 3),(62, 15, 2),(62, 15, 1),(61, 15, 8),(61, 15, 7),(61, 15, 5),(61, 15, 4),(61, 15, 3),(61, 15, 2),(61, 15, 1),(60, 15, 8),(60, 15, 7),(60, 15, 5),(60, 15, 4),(60, 15, 3),(60, 15, 2),(60, 15, 1),(59, 15, 8),(59, 15, 7),(59, 15, 5),(59, 15, 4),(59, 15, 3),(59, 15, 2),(59, 15, 1),(58, 15, 8),(58, 15, 7),(58, 15, 5),(58, 15, 4),(58, 15, 3),(58, 15, 2),(58, 15, 1),(57, 15, 8),(57, 15, 7),(57, 15, 5),(57, 15, 4),(57, 15, 3),(57, 15, 2),(57, 15, 1),(56, 15, 8),(56, 15, 7),(56, 15, 5),(56, 15, 4),(56, 15, 3),(56, 15, 2),(56, 15, 1),(55, 15, 8),(55, 15, 7),(55, 15, 5),(55, 15, 4),(55, 15, 3),(55, 15, 2),(55, 15, 1),(54, 15, 8),(54, 15, 7),(54, 15, 5),(54, 15, 4),(54, 15, 3),(54, 15, 2),(54, 15, 1),(53, 15, 8),(53, 15, 7),(53, 15, 5),(53, 15, 4),(53, 15, 3),(53, 15, 2),(53, 15, 1),(52, 15, 8),(52, 15, 7),(52, 15, 5),(52, 15, 4),(52, 15, 3),(52, 15, 2),(52, 15, 1),(51, 15, 8),(51, 15, 7),(51, 15, 5),(51, 15, 4),(51, 15, 3),(51, 15, 2),(51, 15, 1),(50, 15, 8),(50, 15, 7),(50, 15, 5),(50, 15, 4),(50, 15, 3),(50, 15, 2),(50, 15, 1),(49, 15, 8),(49, 15, 7),(49, 15, 5),(49, 15, 4),(49, 15, 3),(49, 15, 2),(49, 15, 1),(48, 15, 8),(48, 15, 7),(48, 15, 5),(48, 15, 4),(48, 15, 3),(48, 15, 2),(48, 15, 1),(47, 15, 8),(47, 15, 7),(47, 15, 5),(47, 15, 4),(47, 15, 3),(47, 15, 2),(47, 15, 1),(46, 15, 8),(46, 15, 7),(46, 15, 5),(46, 15, 4),(46, 15, 3),(46, 15, 2),(46, 15, 1),(42, 15, 8),(42, 15, 7),(42, 15, 5),(42, 15, 4),(42, 15, 3),(42, 15, 2),(42, 15, 1),(41, 15, 8),(41, 15, 7),(41, 15, 5),(41, 15, 4),(41, 15, 3),(41, 15, 2),(41, 15, 1),(40, 15, 8),(40, 15, 7),(40, 15, 5),(40, 15, 4),(40, 15, 3),(40, 15, 2),(40, 15, 1),(39, 15, 8),(39, 15, 7),(39, 15, 5),(39, 15, 4),(39, 15, 3),(39, 15, 2),(39, 15, 1),(38, 15, 8),(38, 15, 7),(38, 15, 5),(38, 15, 4),(38, 15, 3),(38, 15, 2),(38, 15, 1),(37, 15, 8),(37, 15, 7),(37, 15, 5),(37, 15, 4),(37, 15, 3),(37, 15, 2),(37, 15, 1),(36, 15, 8),(36, 15, 7),(36, 15, 5),(36, 15, 4),(36, 15, 3),(36, 15, 2),(36, 15, 1),(35, 15, 8),(35, 15, 7),(35, 15, 5),(35, 15, 4),(35, 15, 3),(35, 15, 2),(35, 15, 1),(34, 15, 8),(34, 15, 7),(34, 15, 5),(34, 15, 4),(34, 15, 3),(34, 15, 2),(34, 15, 1),(33, 15, 8),(33, 15, 7),(33, 15, 5),(33, 15, 4),(33, 15, 3),(33, 15, 2),(33, 15, 1),(32, 15, 8),(32, 15, 7),(32, 15, 5),(32, 15, 4),(32, 15, 3),(32, 15, 2),(32, 15, 1),(31, 15, 8),(31, 15, 7),(31, 15, 5),(31, 15, 4),(31, 15, 3),(31, 15, 2),(31, 15, 1),(30, 15, 8),(30, 15, 7),(30, 15, 5),(30, 15, 4),(30, 15, 3),(30, 15, 2),(30, 15, 1),(29, 15, 8),(29, 15, 7),(29, 15, 5),(29, 15, 4),(29, 15, 3),(29, 15, 2),(29, 15, 1),(28, 15, 8),(28, 15, 7),(28, 15, 5),(28, 15, 4),(28, 15, 3),(28, 15, 2),(28, 15, 1),(27, 15, 8),(27, 15, 7),(27, 15, 5),(27, 15, 4),(27, 15, 3),(27, 15, 2),(27, 15, 1),(26, 15, 8),(26, 15, 7),(26, 15, 5),(26, 15, 4),(26, 15, 3),(26, 15, 2),(26, 15, 1),(25, 15, 8),(25, 15, 7),(25, 15, 5),(25, 15, 4),(25, 15, 3),(25, 15, 2),(25, 15, 1),(24, 15, 8),(24, 15, 7),(24, 15, 5),(24, 15, 4),(24, 15, 3),(24, 15, 2),(24, 15, 1),(23, 15, 8),(23, 15, 7),(23, 15, 5),(23, 15, 4),(23, 15, 3),(23, 15, 2),(23, 15, 1),(22, 15, 8),(22, 15, 7),(22, 15, 5),(22, 15, 4),(22, 15, 3),(22, 15, 2),(22, 15, 1),(21, 15, 8),(21, 15, 7),(21, 15, 5),(21, 15, 4),(21, 15, 3),(21, 15, 2),(21, 15, 1),(20, 15, 8),(20, 15, 7),(20, 15, 5),(20, 15, 4),(20, 15, 3),(20, 15, 2),(20, 15, 1),(19, 15, 8),(19, 15, 7),(19, 15, 5),(19, 15, 4),(19, 15, 3),(19, 15, 2),(19, 15, 1),(18, 15, 8),(18, 15, 7),(18, 15, 5),(18, 15, 4),(18, 15, 3),(18, 15, 2),(18, 15, 1),(17, 15, 8),(17, 15, 7),(17, 15, 5),(17, 15, 4),(17, 15, 3),(17, 15, 2),(17, 15, 1),(16, 15, 8),(16, 15, 7),(16, 15, 5),(16, 15, 4),(16, 15, 3),(16, 15, 2),(16, 15, 1),(15, 15, 8),(15, 15, 7),(15, 15, 5),(15, 15, 4),(15, 15, 3),(15, 15, 2),(15, 15, 1),(14, 15, 8),(14, 15, 7),(14, 15, 5),(14, 15, 4),(14, 15, 3),(14, 15, 2),(14, 15, 1),(13, 15, 8),(13, 15, 7),(13, 15, 5),(13, 15, 4),(13, 15, 3),(13, 15, 2),(13, 15, 1),(12, 15, 8),(12, 15, 7),(12, 15, 5),(12, 15, 4),(12, 15, 3),(12, 15, 2),(12, 15, 1),(11, 15, 8),(11, 15, 7),(11, 15, 5),(11, 15, 4),(11, 15, 3),(11, 15, 2),(11, 15, 1),(10, 15, 8),(10, 15, 7),(10, 15, 5),(10, 15, 4),(10, 15, 3),(10, 15, 2),(10, 15, 1),(9, 15, 8),(9, 15, 7),(9, 15, 5),(9, 15, 4),(9, 15, 3),(9, 15, 2),(9, 15, 1),(8, 15, 8),(8, 15, 7),(8, 15, 5),(8, 15, 4),(8, 15, 3),(8, 15, 2),(8, 15, 1),(7, 15, 8),(7, 15, 7),(7, 15, 5),(7, 15, 4),(7, 15, 3),(7, 15, 2),(7, 15, 1),(6, 15, 8),(6, 15, 7),(6, 15, 5),(6, 15, 4),(6, 15, 3),(6, 15, 2),(6, 15, 1),(5, 15, 8),(5, 15, 7),(5, 15, 5),(5, 15, 4),(5, 15, 3),(5, 15, 2),(5, 15, 1),(4, 15, 8),(4, 15, 7),(4, 15, 5),(4, 15, 4),(4, 15, 3),(4, 15, 2),(4, 15, 1),(3, 15, 8),(3, 15, 7),(3, 15, 5),(3, 15, 4),(3, 15, 3),(3, 15, 2),(3, 15, 1),(2, 15, 8),(2, 15, 7),(2, 15, 5),(2, 15, 4),(2, 15, 3),(2, 15, 2),(2, 15, 1),(1, 15, 8),(1, 15, 7),(1, 15, 5),(1, 15, 4),(1, 15, 3),(1, 15, 2),(1, 15, 1);
INSERT IGNORE INTO `permission_functionality_map` (`function_id`, `group_id`, `status`) 
SELECT 81, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 81, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 81, users_groups_id, 6 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 81, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 81, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 81, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 81, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 81, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 80, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 80, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 80, users_groups_id, 6 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 80, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 80, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 80, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 80, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 80, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 79, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 79, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 79, users_groups_id, 6 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 79, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 79, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 79, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 79, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 79, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 78, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 78, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 78, users_groups_id, 6 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 78, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 78, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 78, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 78, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 78, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 77, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 77, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 77, users_groups_id, 6 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 77, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 77, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 77, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 77, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 77, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 76, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 76, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 76, users_groups_id, 6 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 76, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 76, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 76, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 76, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 76, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 75, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 75, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 75, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 75, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 75, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 75, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 75, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 74, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 74, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 74, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 74, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 74, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 74, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 74, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 73, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 73, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 73, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 73, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 73, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 73, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 73, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 72, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 72, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 72, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 72, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 72, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 72, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 72, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 64, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 64, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 64, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 64, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 64, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 64, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 64, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 63, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 63, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 63, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 63, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 63, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 63, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 63, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 62, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 62, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 62, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 62, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 62, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 62, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 62, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 61, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 61, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 61, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 61, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 61, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 61, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 61, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 60, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 60, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 60, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 60, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 60, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 60, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 60, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 59, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 59, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 59, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 59, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 59, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 59, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 59, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 58, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 58, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 58, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 58, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 58, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 58, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 58, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 57, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 57, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 57, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 57, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 57, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 57, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 57, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 56, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 56, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 56, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 56, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 56, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 56, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 56, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 55, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 55, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 55, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 55, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 55, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 55, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 55, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 54, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 54, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 54, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 54, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 54, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 54, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 54, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 53, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 53, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 53, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 53, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 53, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 53, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 53, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 52, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 52, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 52, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 52, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 52, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 52, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 52, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 51, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 51, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 51, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 51, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 51, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 51, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 51, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 50, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 50, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 50, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 50, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 50, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 50, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 50, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 49, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 49, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 49, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 49, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 49, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 49, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 49, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 48, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 48, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 48, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 48, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 48, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 48, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 48, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 47, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 47, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 47, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 47, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 47, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 47, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 47, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 46, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 46, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 46, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 46, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 46, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 46, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 46, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 42, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 42, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 42, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 42, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 42, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 42, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 42, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 41, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 41, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 41, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 41, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 41, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 41, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 41, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 40, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 40, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 40, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 40, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 40, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 40, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 40, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 39, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 39, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 39, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 39, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 39, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 39, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 39, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 38, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 38, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 38, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 38, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 38, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 38, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 38, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 37, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 37, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 37, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 37, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 37, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 37, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 37, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 36, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 36, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 36, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 36, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 36, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 36, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 36, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 35, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 35, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 35, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 35, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 35, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 35, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 35, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 34, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 34, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 34, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 34, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 34, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 34, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 34, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 33, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 33, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 33, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 33, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 33, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 33, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 33, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 32, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 32, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 32, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 32, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 32, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 32, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 32, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 31, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 31, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 31, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 31, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 31, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 31, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 31, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 30, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 30, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 30, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 30, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 30, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 30, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 30, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 29, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 29, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 29, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 29, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 29, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 29, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 29, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 28, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 28, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 28, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 28, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 28, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 28, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 28, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 27, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 27, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 27, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 27, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 27, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 27, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 27, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 26, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 26, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 26, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 26, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 26, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 26, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 26, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 25, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 25, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 25, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 25, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 25, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 25, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 25, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 24, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 24, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 24, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 24, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 24, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 24, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 24, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 23, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 23, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 23, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 23, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 23, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 23, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 23, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 22, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 22, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 22, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 22, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 22, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 22, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 22, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 21, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 21, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 21, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 21, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 21, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 21, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 21, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 20, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 20, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 20, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 20, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 20, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 20, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 20, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 19, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 19, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 19, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 19, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 19, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 19, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 19, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 18, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 18, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 18, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 18, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 18, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 18, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 18, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 17, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 17, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 17, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 17, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 17, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 17, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 17, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 16, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 16, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 16, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 16, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 16, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 16, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 16, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 15, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 15, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 15, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 15, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 15, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 15, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 15, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 14, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 14, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 14, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 14, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 14, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 14, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 14, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 13, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 13, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 13, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 13, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 13, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 13, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 13, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 12, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 12, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 12, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 12, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 12, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 12, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 12, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 11, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 11, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 11, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 11, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 11, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 11, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 11, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 10, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 10, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 10, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 10, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 10, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 10, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 10, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 9, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 9, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 9, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 9, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 9, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 9, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 9, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 8, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 8, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 8, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 8, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 8, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 8, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 8, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 7, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 7, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 7, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 7, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 7, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 7, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 7, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 6, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 6, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 6, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 6, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 6, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 6, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 6, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 5, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 5, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 5, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 5, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 5, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 5, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 5, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 4, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 4, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 4, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 4, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 4, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 4, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 4, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 3, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 3, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 3, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 3, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 3, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 3, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 3, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 2, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 2, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 2, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 2, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 2, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 2, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 2, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 1, users_groups_id, 8 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 1, users_groups_id, 7 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 1, users_groups_id, 5 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 1, users_groups_id, 4 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 1, users_groups_id, 3 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 1, users_groups_id, 2 FROM users_groups WHERE users_groups_name='Project manager' UNION ALL 
SELECT 1, users_groups_id, 1 FROM users_groups WHERE users_groups_name='Project manager';